version: '3'

services:
  traefik:
    logging:
      driver: "json-file"
      options:
        max-size: 50m


    image: traefik:1.7
    restart: always
    environment:
      TZ: America/Sao_Paulo
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./certs:/certs/:rw
      - ./data/:/data/:rw
    labels:
      - "traefik.frontend.rule=Host:traefik.elotech.localnet"
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

networks:
  webgateway:
    driver: bridge
